/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swingCustomer;

import com.cdi.g3.common.exception.ObjectNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Apotheas
 */
public class HomePageCustomer extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePageCustomer() throws ObjectNotFoundException {
        initComponents();
        JPanelFormBooksCustomer panelBooks = new JPanelFormBooksCustomer();
        jInternalFrameBooks.setContentPane(panelBooks);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneHomePage = new javax.swing.JTabbedPane();
        jInternalFrameBooks = new javax.swing.JInternalFrame();
        jInternalFrameOrders = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jTabbedPaneHomePage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Management System", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jInternalFrameBooks.setVisible(true);

        javax.swing.GroupLayout jInternalFrameBooksLayout = new javax.swing.GroupLayout(jInternalFrameBooks.getContentPane());
        jInternalFrameBooks.getContentPane().setLayout(jInternalFrameBooksLayout);
        jInternalFrameBooksLayout.setHorizontalGroup(
            jInternalFrameBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jInternalFrameBooksLayout.setVerticalGroup(
            jInternalFrameBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPaneHomePage.addTab("Books", jInternalFrameBooks);

        jInternalFrameOrders.setVisible(true);

        javax.swing.GroupLayout jInternalFrameOrdersLayout = new javax.swing.GroupLayout(jInternalFrameOrders.getContentPane());
        jInternalFrameOrders.getContentPane().setLayout(jInternalFrameOrdersLayout);
        jInternalFrameOrdersLayout.setHorizontalGroup(
            jInternalFrameOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jInternalFrameOrdersLayout.setVerticalGroup(
            jInternalFrameOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPaneHomePage.addTab("Orders", jInternalFrameOrders);

        getContentPane().add(jTabbedPaneHomePage);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrameBooks;
    private javax.swing.JInternalFrame jInternalFrameOrders;
    private javax.swing.JTabbedPane jTabbedPaneHomePage;
    // End of variables declaration//GEN-END:variables
}
